# Generated by Django 3.2.9 on 2021-12-05 11:47

import bot.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_bot', models.BooleanField(default=False)),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('bot_can_message', models.BooleanField(default=True)),
                ('is_telegram_user', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='tg_user', serialize=False, to='auth.user')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('date', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=64)),
                ('data', models.JSONField(encoder=bot.models.JSONEncoder)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='bot.user')),
            ],
            options={
                'ordering': ['message_id'],
                'unique_together': {('message_id', 'user')},
            },
        ),
    ]
