# Generated by Django 3.2.9 on 2021-12-06 02:42

import bot.models
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler_id', models.PositiveSmallIntegerField()),
                ('group_id', models.BigIntegerField()),
                ('fn', picklefield.fields.PickledObjectField(editable=False)),
                ('args', picklefield.fields.PickledObjectField(editable=False)),
                ('kwargs', picklefield.fields.PickledObjectField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('santa', 'Santa'), ('saint_nicholas', 'Saint Nicholas')], default='santa', max_length=256)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Register opened'), (1, 'Register closed'), (2, 'Participants are already distributed')], default=0)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=2048)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_events', to='bot.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishes', models.TextField(blank=True, null=True)),
                ('messages_as_santa', models.JSONField(default=list)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participants', to='bot.event')),
                ('secret_good_buddy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_santa', to='bot.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participants', to='bot.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForwardMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(encoder=bot.models.JSONEncoder)),
                ('from_participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_messages', to='bot.participant')),
                ('to_participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_messages', to='bot.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='message',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='bot.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='active_participant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_active_user', to='bot.participant'),
        ),
    ]
