# Generated by Django 3.2.9 on 2021-12-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_message_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forwardmessage',
            name='data',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='messages_as_santa',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='wishes',
        ),
        migrations.AddField(
            model_name='forwardmessage',
            name='message_id',
            field=models.BigIntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forwardmessage',
            name='type',
            field=models.CharField(choices=[('buddy', 'Secret Good Buddy'), ('santa', 'Secret Santa')], default='santa', max_length=256),
            preserve_default=False,
        ),
    ]
