# Generated by Django 3.2.9 on 2021-12-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20211211_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Register opened'), (1, 'Register closed'), (2, 'Participants are already distributed'), (3, 'Event ended')], default=0),
        ),
    ]
